### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by Siddaramappa** [Hujjat/vue-shop#1]
hi i am siddu new to vue js frame work i gone through video which u posted on youtube it was really gud thanks for posting the video. the issue what i am facing is i cloned ur git repo then while installing npm i getting this error can u please help me out it will be helpful thanks!!
![vue-cli-issue](https://user-images.githubusercontent.com/41416742/52537206-e529c480-2d89-11e9-8bb0-3935e4d88929.png)

**Comment by Hujjat** [comment]
Hi buddy, 

There is nothing wrong with the npm command. Those are just some warnings. Don't worry about it :) 

If your code is not working!! let me know.
