### ISSUE TITLE
Error when type $ npm run serve  

### ISSUE THREAD

**Issue by ElectroArmy** [Hujjat/vue-shop#2]
$ npm run serve

> vue-shop@0.1.0 serve C:\xampp\htdocs\laravelapp\vue-shop
> vue-cli-service serve

 INFO  Starting development server...
 94% after seal ERROR  Failed to compile with 8 errors4:01:09 PM

These relative modules were not found:

* ../firebase in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Login.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/sections/ProductList.vue?vue&type=script&lang=js& and 4 others
* ./firebase in ./src/main.js, ./src/router.js

**Comment by AhmedVohra** [comment]
I'm going through this error too. Can someone help?

**Comment by Darshan197** [comment]
use This
window.$ = window.jQuery = require('jquery');

Don't Import Like 
import JQuery from "jquery";

**Comment by masumluf** [comment]
Go to src folder and change firebase-example.js to firebase.js also insert your credential into the firebase  config file. it will work
